# Generated by Django 4.2.8 on 2024-11-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='control_event',
        ),
        migrations.AddField(
            model_name='subject',
            name='control_event',
            field=models.ManyToManyField(to='core.controlevent'),
        ),
    ]
