# Generated by Django 4.2.8 on 2024-11-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_subject_control_event_subject_control_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='week_day_number',
            field=models.IntegerField(null=True),
        ),
    ]
