# Generated by Django 4.2.8 on 2024-11-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_bio_remove_customuser_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
    ]
