# Generated by Django 4.2.8 on 2024-11-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_week_day_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='control_event',
        ),
        migrations.AddField(
            model_name='controlevent',
            name='subjectId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
            preserve_default=False,
        ),
    ]
