# Generated by Django 4.2.8 on 2024-11-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_subject_control_event_controlevent_subjectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmaterials',
            name='content',
            field=models.FileField(upload_to='additional_materials'),
        ),
    ]
