# Generated by Django 4.2.8 on 2024-11-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lesson_lessonlocation_subject_typeoflesson_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='groupId',
            field=models.ManyToManyField(blank=True, related_name='groups', to='core.studentgroup'),
        ),
    ]
