# Generated by Django 4.2.8 on 2024-11-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_additionalmaterials_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_elective',
            field=models.BooleanField(null=True),
        ),
    ]
