# Generated by Django 4.2.8 on 2024-11-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studentgroup_alter_lesson_groupid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='lessonlocation',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'Группа студентов', 'verbose_name_plural': 'Группы студентов'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='typeoflesson',
            options={'verbose_name': 'Тип занятия', 'verbose_name_plural': 'Типы занятий'},
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='lesson',
        ),
        migrations.AlterModelTable(
            name='lessonlocation',
            table='lessonlocation',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
        migrations.AlterModelTable(
            name='studentgroup',
            table='studentgroup',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
        migrations.AlterModelTable(
            name='typeoflesson',
            table='typeoflesson',
        ),
    ]
