# Generated by Django 4.2.8 on 2024-11-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_additionalmaterials_controlwork_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='students',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(null=True, to='core.studentgroup'),
        ),
    ]
