# Generated by Django 4.2.8 on 2024-11-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lesson_options_alter_lessonlocation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeoflesson',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelTable(
            name='lessonlocation',
            table='LessonLocation',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='Subject',
        ),
        migrations.AlterModelTable(
            name='typeoflesson',
            table='Тип лекции',
        ),
    ]
