# Generated by Django 4.2.8 on 2024-11-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subject_is_elective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_groups',
            field=models.ManyToManyField(related_name='student_groups', to='core.studentgroup'),
        ),
    ]
