# Generated by Django 4.2.8 on 2024-11-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_studentgroup_students_alter_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(to='core.studentgroup'),
        ),
    ]
