# Generated by Django 4.2.8 on 2024-11-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customuser_student_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hourse_number',
            field=models.IntegerField(default=0),
        ),
    ]
