# Generated by Django 4.2.8 on 2024-11-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subject_hourse_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='hourse_number',
            new_name='hours_number',
        ),
    ]
