# Generated by Django 4.2.8 on 2024-11-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_groupss_customuser_student_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='number',
            new_name='lesson_number',
        ),
        migrations.AddField(
            model_name='lesson',
            name='week_number',
            field=models.IntegerField(null=True),
        ),
    ]
