# Generated by Django 4.2.8 on 2024-11-18 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lesson_subjectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Дополнительный материал',
                'verbose_name_plural': 'Дополнительные материалы',
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='ControlWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Контрольные работы',
                'verbose_name_plural': 'Контрольные работы',
                'db_table': 'controlwork',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table': 'test',
            },
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='lessons',
            field=models.ManyToManyField(to='core.typeoflesson'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(to='core.studentgroup'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='groupId',
            field=models.ManyToManyField(blank=True, to='core.studentgroup'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacherId',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LessonArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField(default=False)),
                ('lessonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lesson')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Архив занятий',
                'verbose_name_plural': 'Архив занятий',
                'db_table': 'lessonarchive',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='additional_materials',
            field=models.ManyToManyField(to='core.additionalmaterials'),
        ),
        migrations.AddField(
            model_name='subject',
            name='control_works',
            field=models.ManyToManyField(to='core.controlwork'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tests',
            field=models.ManyToManyField(to='core.test'),
        ),
    ]
